rwth-i6/sisyphus

- sisyphus/graph.py
I've added the comparison of `pattern` and the visible name of each job.
> Added support for finding jobs by their visible name

- sisyphus/toolkit.py
choose between remove, move, dryrun
> add run mode to remove_job_and_descendants

- sisyphus/simple_linux_utility_for_resource_management_engine.py
Additional engine class for the slurm scheduling engine (https://slurm.schedmd.com/)
> add slurm engine

- docs/conf.py
- docs/index.rst
I think that the alabaster theme is very inconvenient to read, so I would like to change the theme to the more common RTD theme.
> changed docs theme

- sisyphus/loader.py
this adds a check for the config files. must be in config folder of be a root level named config.py
@curufinwe @critias is this wanted? would this break your setup?
> add check for config files

- docs/index.rst
just a few lines about config files
> adds info for config.py and config folder setup

- sisyphus/simple_linux_utility_for_resource_management_engine.py
On my AWS cluster I need to use --mem instead of --mem-per-cpu, this adding an option to the Slurm engine.
> Add memory_allocation_type to slurm engine

- sisyphus/global_settings.py
To natively support the new setups, then there is no need to modify anything in the settings.
> automatically add recipe folder to path

- sisyphus/delayed_ops.py
- tests/delayed_ops_unittest.py
Add delayed ops for pow operator
> Added delayed ops for pow operator

- sisyphus/delayed_ops.py
- tests/delayed_ops_unittest.py
Added two new methods to Variables:
- fallback: If Variable is not set yet the given default value will be returned
- rformat: Reversed format, a.rformat(b) == b.format(a), useful as shortcut to created a DelayedFormat object.
Also is_set is too propagated backwards through a chain of DelayedBase Objects.
> Added fallback and rformat to Delayed objects

- sisyphus/global_settings.py
- sisyphus/job_path.py
Added setting to make accessing of Variables and Paths more restrictive.
> Variable not set

- sisyphus/graph.py
> Simplify path checking logic in SISGraph

- requirements.txt
Sisyphus does not start without it.
> add flask to requirements

- example/config/__init__.py
- sisyphus/job.py
- sisyphus/job_path.py
A possible solution to:
https://github.com/rwth-i6/i6_core/issues/198
Todo: I need to split the common functionality between Path and Variable into a new class, instead of having Variable as a subclass of Path to clean up the code a bit.
> Apply __add__ and __getitem__ directly on Path

- sisyphus/worker.py
> Bugfix for worker_wrapper on localengine

- sisyphus/loader.py
> allow config to be loaded from anywhere

- sisyphus/delayed_ops.py
- tests/delayed_ops_unittest.py
Needed for https://github.com/rwth-i6/i6_core/pull/307
> add DelayedJoin

- setup.py
> Fix packaging of templates

- sisyphus/engine.py
- sisyphus/global_settings.py
- sisyphus/task.py
- Some cleanup of the automatic requirement update 
- Changed requirements in the recipes will now overwrite automatic requirement updates.
> Changed requirements in the recipes will overwrite automatic requirement updates

- sisyphus/delayed_ops.py
I realized that div is missing as supported operation for DelayedOps
> Added support for delayed div operations

- sisyphus/task.py
Closes #129 
I think a small docs update is enough here.
> Document Task.parallel's batching behavior

- sisyphus/job.py
- sisyphus/manager.py
> move setting up job after move into manager

- sisyphus/manager.py
> JobCleaner, properly stops threads at close

- sisyphus/manager.py
For debugging, when you want to interactively start the jobs, but they are not created yet, I found this a useful option (otherwise you either would need to do it via console, or start the manager and then immediately cancel the job again).
Alongside this change, some smaller other changes:
* Also some extra logging for all the options.
* Also renamed "holded" -> "held".
* Also reordered the options in UI a bit, so that the most common (start manager) is first. Same order then also in the code.
> sis manager, option to setup runnable jobs

- sisyphus/job.py
This has always annoyed me before. This should make it much easier to find job inputs in a large list of them.
> Sort data written to job info file

- sisyphus/job.py
> Job _sis_finished check, skip when called too fast

- .github/workflows/ruff.yml
- example/recipe/pipeline/__init__.py
- pyproject.toml
- sisyphus/__main__.py
- sisyphus/aws_batch_engine.py
- sisyphus/block.py
- sisyphus/cleaner.py
- sisyphus/engine.py
- sisyphus/graph.py
- sisyphus/job.py
- sisyphus/job_path.py
- sisyphus/localengine.py
- sisyphus/manager.py
- sisyphus/manager_ui.py
- sisyphus/shortcuts.py
- sisyphus/toolkit.py
- sisyphus/worker.py
- tests/hash_unittest.py
- tests/job_path_unittest.py
- tools/ducttape2sis.py
As discussed offline today the ruff formatter is faster, as easy to use, and yields equal or better results compared to black. 
We therefore want to update the formatter to ruff.
> Change formatter to ruff

- sisyphus/global_settings.py
- sisyphus/job.py
The stack depth check was broken if it was -1 or None.
Fix #259
> Fix stack depth check
