- sisyphus/job.py
- sisyphus/manager.py
There was a request to add dynamic information into the manager view. You can override the function to provide additional dynamic information about the job, which can e.g. be the perplexity of a running model training job.
> added manager callback function to display dynamic job information

- sisyphus/toolkit.py
By storing the list of directories in a temporary file, the number of directories no longer influences the command length.
> Fixed issue with argument length during the directory size computation

- sisyphus/job.py
This is a very common mistake in sisyphus configurations.
> added warning if a Job instance is passed as argument

- sisyphus/global_settings.py
Miguel found this new bug, as TMPDIR defaults to "/var/tmp" in our bashrc
> fixed missing path separator for tempdir paths not ending with a slash

- sisyphus/global_settings.py
- sisyphus/job.py
I thought this to be a very useful thing, it can be used to determine where a job was created.
Also, you can find all jobs belonging to a single call, e.g:
```
for job in j:
first_st = job._sis_stacktrace[0][0]
if first_st[0] == "/u/rossenbach/experiments/switchboard_test/config/E2ESystem.py" and first_st[1] == 229:
print(job)
```
will list all jobs that are created in E2ESystem.py line 229:
```
225: j = CRNNSprintSearchJob(search_csp=self.csp[search_corpus],
226:                                feature_flow=self.feature_flows[feature_corpus][feature_flow],
227:                                crnn_config=crnn_config,
228:                                num_classes=self.functor_value(num_classes),
229:                                **kwargs)
```
> added optional stacktrace to jobs, can be used in console

- sisyphus/graph.py
A job can be finished without being runnable (cleanup deletions of inputs), leading to runnable jobs that are not required. This is solved by this fix.
> fixed issue with wrong return value of get_unfinished_jobs

- sisyphus/__main__.py
- sisyphus/manager.py
In combination with the `-r` flag, this ensures that the manager starts whether there are jobs in the error state or not.
> Added flag to optionally ignore jobs in error state when the manager is started

- sisyphus/global_settings.py
- sisyphus/job.py
The number of locks that can be acquired is limited by some system setting. I'm not certain which one it is, but it can be tested by this program:
```
import multiprocessing
a = []
try:
for i in range(100000):
a.append(multiprocessing.Lock())
print("Success")
except:
print("Error at lock number %d" % i)
```
For me, this returns `Error at lock number 65270`.
If every job gets its own lock, this means that I cannot have more than about 65000 jobs in my tree. I usually don't, but if I want to start the cleaner, I have to include every experiment I've ever started. This led to the error message `OSError: [Errno 12] Cannot allocate memory` when no more locks could be acquired.
This PR fixes this issue by reusing the locks once a configurable threshold is reached.
> Limited number of acquired locks

- sisyphus/toolkit.py
Commit ec7de9b1eb7d04dc38d48f0e8628ea716e50026c introduced f-strings, which are not supported for python versions older than 3.6. By using %-formatting instead, we don't lose support for older python versions.
> Avoid f-strings to ensure compatibility to python versions < 3.6

- sisyphus/job.py
Previously `_sis_delete()` would throw an error for symlinks (as it tries to remove them via `shutil.rmtree(path)`.
Fixed this problem by adding a case distinction.
> Made _sis_delete() compatible with symlinks

- sisyphus/__main__.py
- sisyphus/manager.py
- sisyphus/notebook.py
- sisyphus/toolkit.py
I think there should be a "clear" option for interrupted jobs that don't continue on their own.
As I didn't find anything, I implemented it in the same way it's done for error jobs.
> Added clear option for interrupted jobs

- sisyphus/toolkit.py
There are sometimes errors during removal (etc open folder or some leftover .nfs files), but I do not want the removal to stop completely.
> do not stop remove on error

- sisyphus/visualize.py
visualize_block currently crashes since merged_links is not defined
> Bugfix in visualize_block

- sisyphus/son_of_grid_engine.py
Current situation: h_fsize in the SGE Engine is hardcoded to 50GB
Change: indroduction of a new key for the requirements dict: "file_size"
Effect: h_fsize can be set by user. The default value remains at 50GB
> make call to h_fsize non hard-coded

- sisyphus/simple_linux_utility_for_resource_management_engine.py
On local Slurm setups you might want not configure memory as a resource, but Slurm will give an error if you try to assign jobs memory when not configured.
> add has_memory_resource parameter for slurm

- README.md
- docs/conf.py
- docs/index.rst
- requirements.txt
Maybe adding mermaid diagrams for sphinx could improve documentation?
Here I add a diagram for the example. It is still far away from being clear what the example is supposed to do. I spent quite some time and still feel unsure about it.
It feels like the example is forcefully using as many features as possible. While maybe logical, it ends up being very complicated for a novice to get an idea of what sisyphus is supposed to do.
Maybe smaller examples that aim to show only certain features would make more sense. The users can put them together on their own.
> add workflow diagramm for the example in the documentation using mermaid

- sisyphus/global_settings.py
- sisyphus/job.py
- sisyphus/loader.py
- sisyphus/toolkit.py
These changes allows to store the recipes without the recipe prefix in arbitrary locations by settings IMPORT_PATHS in settings.py accordingly. e.g.: IMPORT_PATHS = ['config', 'recipe/'] will load everything inside of the recipe/ folder without the recipe prefix.
> Allow more flexibility for recipe loading

- .flake8
- sisyphus/__main__.py
- sisyphus/global_settings.py
- sisyphus/job.py
- sisyphus/job_path.py
- sisyphus/manager.py
- sisyphus/tools.py
- tests/job_path_unittest.py
Creates a file to cache all finished jobs to one central file. Should speed up the startup time of systems with many finished jobs which use variables for reports etc.
> Added possibility to cache results of finished jobs

- sisyphus/global_settings.py
- sisyphus/job_path.py
I thought it is a good idea to add a gs variable that prohibits resolving any "Delayed" object  while still being in the "graph" thread. I saw that this is the most common error when working with Sisyphus.
> add worker check for Delayed

- sisyphus/global_constants.py
- sisyphus/global_settings.py
- sisyphus/job.py
- sisyphus/task.py
This code was originally added to log when a job output was used the last time.
I would like to remove it since it's not used by anybody afaik, adds an unused directory to every job and I don't want to support this feature in the future.
Any objections?
> Removed code to log last file usage since it didn't prove useful in practice

- sisyphus/graph.py
The path argument in get_job_from_path is overwritten by the variable in the inner loop.
This causes that get_job_from_path always returns None.
Noticed this when trying to migrate a large graph.
> Bugfix for get_job_from_path

- sisyphus/engine.py
- sisyphus/task.py
This moves the call of `gs.check_engine_limits` from `Task.update_rqmt` to `EngineBase.get_rqmt`. This way the requirements are already checked on the initial submit and not only after the requirements are updated.
This helps to avoid issues if the initial job requirements are already too high for the current engine.
Also based on the documentation in global_settings.py, I expected that the method would be called also on the first submission of tasks.
> Call check_engine_limits on initial submit

- sisyphus/tools.py
Fixup for #85.
Should make #88 obsolete.
> extract_paths more efficient, small fixup

- sisyphus/graph.py
This gives me some huge speedup, of a big GMM pipeline, from hours of runtime (I let it run for about 30 mins and then stopped, so I don't actually know) down to 20 secs runtime.
This is with `GRAPH_WORKER = 1`.
The main problem is that this did not keep track of visited nodes for this case.
But also, when comparing this implementation now to the case of `GRAPH_WORKER > 1` (e.g. `GRAPH_WORKER = 16`), it's more than twice as fast. And this is expected: I don't see any reason why a multi-threaded implementation can make it any faster:
* Any computation in Python is actually single threaded due to the GIL.
* There is a lot of overhead involved with the multithreading logic.
* If the FS is the bottleneck, there is also no point in having it multithreaded.
So, I would even suggest to go …
> SISGraph for_all_nodes more efficient single-threaded

- sisyphus/job_path.py
- tests/job_path_unittest.py
Addressing issue https://github.com/rwth-i6/sisyphus/issues/96
> Fixed inconsistent hash_overwrite after copy_append and join_right

- sisyphus/son_of_grid_engine.py
The `getiterator()` function in `xml.etree.ElementTree` was deprecated and got removed in python3.9. This replaces the function by `iter()`.
> XML ElementTree fix for python3.9+

- sisyphus/cleaner.py
Small PR to change the msg. that shows when using the clenup keep value function.
I found "Keep Value too low" confusing, since to me it suggested that the value I set was too low instead of removing jobs with too low value. 
The new msg. is just a suggestion from me, I am fine with other suggestions if you dont like this one.
> change keep value remove msg

- sisyphus/loader.py
Extension to #91, #100.
E.g. when you now do:
```
sis m recipe/i6_experiments/users/zeyer/experiments/exp2022_07_21_transducer/pipeline_swb_2020.py
```
When having `"recipe/"` in my `gs.IMPORT_PATHS`, I want that it loads the module `i6_experiments.users.zeyer.experiments.exp2022_07_21_transducer.pipeline_swb_2020`, not with the `recipe.` prefix.
To be fair, it's a bit ambiguous when you have both `"recipe/"` and `"recipe"`. Then both work but then it depends on how the remaining recipes are implemented, and whether their imports are using the `recipe.` prefix or not. But I think most don't use it, e.g. [i6_core](https://github.com/rwth-i6/i6_core/blob/main/returnn/training.py), which is maybe most relevant.
As the main user so far of this feature (#91), I think this gives some priority …
> config from recipe, maybe remove import path prefix

- sisyphus/job_path.py
When `hash_overwrite` is given, it should not matter.
I esp have the cases that I have some resources inside my base dir which I need to reference but I provide a `hash_overwrite` so that no hash is dependent on the absolute path.
I don't just want to disable the warning because the warning is still useful.
> absolute path warning only without hash_overwrite

- sisyphus/global_settings.py
- tests/settings_loader_unittest.py
This PR should fix the bug report in issue https://github.com/rwth-i6/sisyphus/issues/112
Not well tested yet. Main drawback is that DEFAULT_ENVIRONMENT_KEEP and DEFAULT_ENVIRONMENT_SET can not be accessed anymore inside the settings file. I'm not sure if this is really used by anybody.
This PR also allows having multiple settings files.
> Loading settings file using importlib

- sisyphus/aws_batch_engine.py
- sisyphus/load_sharing_facility_engine.py
- sisyphus/localengine.py
- sisyphus/simple_linux_utility_for_resource_management_engine.py
- sisyphus/son_of_grid_engine.py
- sisyphus/task.py
Maps to parallel environment (PE) for SGE, and to ntasks for Slurm, and other engines will throw an exception.
Needed for https://github.com/rwth-i6/i6_core/pull/333.
> multi_node_slots option for rqmt

- .github/workflows/main.yml
The CI runner currently fails with 
```
Error: Version 3.6 with arch x64 not found
```
ubuntu-latest now defaults to ubuntu 22.04 for which python 3.6 is not available anymore.
> Fixes CI by fixing the ubuntu version to 20.04

- CHANGELOG.md
- sisyphus/simple_linux_utility_for_resource_management_engine.py
The memory allocation type in the SLURM engine currently defaults to per_cpu.
I.e. if a task requests `{'cpu': 2, 'mem': 16}` a node with 32GB of memory is requested for the task.
For all other engines (e.g. the sge engine or the local engine) the `mem` rqmt always corresponds to the total memory on a node. I'd have expected that per default the slurm engine behaves identically.
For consistency between different engines, I propose to switch the default from `per_cpu` to `per_node`. This may be a breaking change for some setups, though I'm not aware of any sisyphus users exclusively using slurm.
On the other hand, multiple heavy sisyphus users are going to switch from the sge to slurm soon and are probably not aware of this difference in behaviour and thus will request more memory than …
> Change default memory_allocation_type in SLURM Engine 

- README.md
- setup.py
I really love sisyphus, and I am currently using it in my thesis. However, having to clone the repository and adding `sis` to `PATH` always struck me as kind of cumbersome. This means, for example, that sisyphus won't install itself neatly in any virtualenv. Is there a specific reason for this?
Alternatively adding
```python
entry_points = {
"console_scripts": ["sisyphus=sisyphus.__main__:main","sis=sisyphus.__main__:main"]
}
```
as argument to the setup.py gives the user the ability to install sisyphus directly from VCS with pip in any venv while still giving them access to the `sis` and `sisyphus` shell commands. At least while the venv is activated. This PR implements these quick changes.
Incidentally, this resolves #45 as well, I think.
> New install strategy

- sisyphus/job.py
This PR suggests an update to the warning when using a Job as input:
The old warning e.g. would look like this, where in my opinion its not clear which job was used as an input, to pinpoint the code where this happend:
```
A Job instance was used as argument "corpus" in "<class i6_experiments.users.hilmes.tools.tts.speaker_embeddings.RemoveSpeakerTagsJob'>", this might result in undesired behavior
```
The new code would produce:
```
The Job <alias/Test/pfad/bis/ins/nichts... work/i6_experiments/users/hilmes/tools/tts/speaker_embeddings/RemoveSpeakerTagsJob.pXEVpRnGSiok> was used as argument "corpus
" in "<class 'i6_experiments.users.hilmes.tools.tts.speaker_embeddings.RemoveSpeakerTagsJob'>", this might result in undesired behavior
```
> Update for Job used as argument warning

- sisyphus/job.py
Stacktrace and aliases are to be printed into the job info file.
These changes were tested on:
1. Multiple values of JOB_ADD_STACKTRACE_WITH_DEPTH.
2. Single config and single aliases for a single job.
3. Single config and multiple aliases for a single job.
4. Multiple configs and multiple aliases for a single job.
> Logging more data into "info"

- sisyphus/block.py
- sisyphus/helper.py
- sisyphus/job.py
- sisyphus/job_path.py
- sisyphus/loader.py
- sisyphus/shortcuts.py
- sisyphus/toolkit.py
Added a shortcut to load one or more jobs and display them with dependency using the web interface.
The graph interfaced used blocks group all jobs from a config together. This doesn't happen for loaded jobs, so I'm setting a new root block in sisyphus/helper.py line 18.
While working on that I realized that setting the root block was also broken for async workflows and fixed that as well.
Overall I'm not really happy with the whole block concept. Storing the current block in a global place feels ugly and is really error prone especially for async workflows... Anyway, here it should now be working again.
> Visualize job shortcut

- sisyphus/job.py
fixes #130
In case the import_path contains a symlink, this will avoid unnecessary hops while copying or symlink directly to the final target.
> resolve links during job import

- sisyphus/graph.py
The parameter `required` of `OutputReport` was previously unused. 
The same parameter is used by `OutputCall` to explicitly list all inputs that need to be finished in order for the Call to run - e.g. in case the automatic detection fails. I assume the same functionality was planned for `OutputReport` as well.
Point of contention: the function `update_values(self, report_values)` currently does not have such functionality. Should I add it?
> respect "required" in OutputReport

- sisyphus/simple_linux_utility_for_resource_management_engine.py
The recent change to slurm on our system brought up a painpoint of sisyphus that I had already faced before. We typically have a fixed width for each column when checking the queuing system's status. The job name's column is already the widest of them. However, with my current width of 64 characters  is still not enough, e.g.
```
i6_core.recognition.advanced_tree_search.AdvancedTreeSearchJob.H
```
for a recognition job. I could increase that further, but a nicer alternative could be to change the default name that we give to jobs from the naming scheme above to just
```
AdvancedTreeSearchJob.HckKXQdAFa09
```
In this PR, I propose to introduce `SHORT_JOB_NAMES` as a flag in the global setting which does exactly that.
> Allow setting short job names

- sisyphus/manager.py
For consistency I propose to force the update in the case the user answers the question
```
All calculations are done, print verbose overview (v), update outputs and alias (u), cancel (c)? 
```
with `u` (update).
The flag `force_update` is already set in case of the question 
```
Print verbose overview (v), update aliases and outputs (u), start manager (y), or exit (n)? 
```
when there are still outputs to compute if the user answers `u` or `y`.
(cf. lines 531 nd 536)
> Force update when all calculations are done

- sisyphus/global_settings.py
- sisyphus/manager.py
Sometimes you know that a NN training will not be good, so you cancel it after an early epoch.
One could then remove it from the graph, but 
* this is rather complicated if one uses nested for loops to setup all the jobs
* makes it intransparent why this experiment was removed (i.e. we might still want to see the bad scores of the early epochs)
The next best option is to manually mark the training as HOLD (or ERROR), but then we will still be reminded in the manager about this job, that we do not want any more. (can be really a lot of lines sometimes)
So here I propose a setting `PRINT_HOLD` (default `True` to preserve the old behavior). The manager will skip printing lines for held Jobs if this is set to False. The number of held jobs will still be printed in the overview to remind us of …
> Add option to not print Jobs in HOLD state

- sisyphus/cleaner.py
After discussing this today: There are several options to get the list of unused directories, but none of them is as simple as running `tk.cleaner.cleanup_unused(mode="dryrun")`. You can run `tk.cleaner.cleanup_unused()` and then type `n` when asked `Delete directories?` but it does not feel as safe as doing a dry run right from the beginning. This PR adds the option to do a dry run.
> cleanup_unused: allow dryrun

- sisyphus/cleaner.py
When calling the current code it crashes with: 
```
Calculate size of affected directories? (Y/n): 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 tk.cleaner.cleanup_unused(mode="dryrun")
File ~/src/sisyphus/sisyphus/cleaner.py:316, in cleanup_unused(load_from, job_dirs, mode)
314     job_dirs = list_all_graph_directories()
315 to_remove = search_for_unused(job_dirs, verbose=True)
--> 316 remove_directories(to_remove, 'Not used in graph', mode=mode, force=False)
File ~/src/sisyphus/sisyphus/cleaner.py:235, in remove_directories(dirs, message, move_postfix, mode, force)
233 with tempfile.NamedTemporaryFile() as tmp_file:
234     for directory in dirs:
--> 235 …
```
> Fix Crash when Calculation of size of deleted dirs is asked for

- sisyphus/simple_linux_utility_for_resource_management_engine.py
Sometimes it can be helpful to specify the GPU name even within a given partition for the SLURM engine, e.g., to specify gtx_1080 vs. rtx_2080 in our infrastructure. This PR adds this functionality. To use it, you need to set e.g. `job.rqmt["gpu_name"] = "rtx_2080"`.
> slurm engine: allow setting gpu name

- sisyphus/tools.py
For some reason I have a setup where extract_paths will return the class tk.Path. Not sure why that is in my setup, but in principle we should check for that and not return the class itself if it happens to be in the object.
> Check for class instances of AbstractPath in extract_paths

- sisyphus/loader.py
It might not be set, depending on where the exception was raised, and depending on the entry point of Sisyphus.
[Via](https://github.com/rwth-i6/i6_experiments/actions/runs/6219601859/job/16877982502?pr=175):
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/sisyphus-1.0.0-py3.8.egg/sisyphus/loader.py", line 54, in load_config_file
config = importlib.import_module(module_name)
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 10[14](https://github.com/rwth-i6/i6_experiments/actions/runs/6219601859/job/16877982502?pr=175#step:8:15), in _gcd_import
File "<frozen …
```
> Fix sys.excepthook_org handling

- sisyphus/job.py
> No job cleanup for symlinked job dirs

- sisyphus/simple_linux_utility_for_resource_management_engine.py
> Slurm, fix duplicate jobs

- sisyphus/global_settings.py
- sisyphus/task.py
New options:
- `WAIT_PERIOD_FOR_INPUTS_AVAILABLE`
- `TASK_INPUTS_MUST_BE_AVAILABLE`
Fix #159.
Note that `TASK_INPUTS_MUST_BE_AVAILABLE` is True by default, which can potentially break some old setups, where jobs used an input which was not an existing file but only the prefix of it (e.g. checkpoint file name).
> Task.run wait for inputs

- sisyphus/engine.py
For the case that the `default_rqmt` contains a list (e.g. `default_qsub_args`) we should do a deep rather than a shallow copy.
> use deepcopy for default rqmt

- sisyphus/job.py
This line breaks my type checker (Pyright / Pylance) and makes it think that all instances of specific jobs are of the parent class `Job`. e.g.
```
from sisyphus import Job
class MyJob(Job):
def __init__(self, foo):
self.foo = foo
my_job = MyJob("foo")
print(my_job.foo)
```
The code works, but type checker complains that `sisyphus.Job` has no member `foo`.
Could we remove this line?
> Remove Job assert

- sisyphus/simple_linux_utility_for_resource_management_engine.py
`submit_helper` writes an invalid state to `_task_info_cache`, and then `task_state` returns `STATE_UNKNOWN`, which causes `STATE_INTERRUPTED_RESUMABLE`, which causes a resubmit.
Fix #163.
> Slurm, fix submitting tasks multiple times

- sisyphus/worker.py
Not all exceptions in Task.run will lead to logging_thread.stop(), which is required that the proc does not hang at exit, because logging_thread was not a daemon thread.
We make it a daemon thread now.
And also, we additionally make extra sure that logging_thread.stop() is called.
(Although there are maybe still other rare cases where this is not effective, so the daemon thread property is still important as well.)
Fix #171.
> Fix worker proc hanging at exception

- sisyphus/job.py
As discussed in https://github.com/rwth-i6/sisyphus/pull/166: 
This PR is adding back the assert together with typing information.
> Add TypeVar for Job creation

- sisyphus/global_settings.py
- sisyphus/graph.py
Fix #152.
I used `FINISHED_LOG` as the name for the option to have it consistent with `MEMORY_PROFILE_LOG`.
I used `"log/finished.log"` as the default path to have it consistent with `"log/manager.log.%s"`
from the manager UI.
I thought about whether to have this enabled or disabled by default, and decided that this should not add too much overhead, so we can have this enabled by default.
> Log finished outputs

- sisyphus/global_constants.py
- sisyphus/job.py
- sisyphus/tools.py
- sisyphus/worker.py
As it was discussed in #178.
Fix #178
> Job, possibility to update env vars

- sisyphus/simple_linux_utility_for_resource_management_engine.py
For some reason calling sbatch would interpret the `--wrap` string differently for one of my new setups.
```
sbatch [...] --wrap=apptainer exec --nv --bind /work/asr4 /work/asr4/rossenbach/rescale/pytorch_mixed_precision/apptainer/u22_pytorch2.1_onnx_flashlight_0224_jaist_project.sif sis worker --engine long work/i6_core/returnn/forward/ReturnnForwardJobV2.xT8obDvtAg1w run
[2024-03-04 10:16:31,705] ERROR: Error: sbatch: error: Script arguments not permitted with --wrap option
```
I added quotation marks solving this issue.
> add quotation marks to --wrap for sbatch

- sisyphus/simple_linux_utility_for_resource_management_engine.py
The previous PR #182 only worked correctly when using a gateway. The transfer via ssh -x is the actual problem, thus I here now propose to use `shlex` to do proper automatic string quotation for shell command usage.
> Use shlex for sending commands via gateway.

- CHANGELOG.md
- sisyphus/localengine.py
In the current implementation the LocalEngine always tries to schedule the first runnable task in its input queue (fifo). In cases where this jobs requires resources that are currently not available (e.g. a GPU), the scheduler waits till the resources are available even if there are smaller jobs that could be scheduled now.
As a very simple fix, with this change, if a task cannot be scheduled it is moved to the end of the queue and the next task is checked.
> Improving the scheduling logic of the local engine

- sisyphus/hash.py
- tests/hash_unittest.py
> Keep hash consistent for enum in newer Python versions

- sisyphus/job.py
- sisyphus/task.py
In on of our setups we wanted to use different worker wrapper functions for different parts of the setup.
Therefore I propose to store the currently defined `gs.worker_wrapper` at the creation time of the Job in the Job. Then different parts of the setup can change the worker_wrapper as they go.
> store worker wrapper in Job

- sisyphus/aws_batch_engine.py
- sisyphus/load_sharing_facility_engine.py
- sisyphus/simple_linux_utility_for_resource_management_engine.py
- sisyphus/son_of_grid_engine.py
If the SSH key isn't properly set, sisyphus will schedule stacked queue scan commands which will ask for a password. This will lead to subprocess buildup, which eventually crashes the manager with a `Too many open files` error.
I've also changed the hardcoded 30 second interval for an interval depending on `gs.WAIT_PERIOD_BETWEEN_CHECKS`, which I find makes more sense. <- Edit: not anymore, see below.
Fix #190.
> Add timeout to SSH queue scan command

- sisyphus/task.py
Also removed Python 2 style code to derive from object.
I did not cover `update_rqmt` yet because this would require `Protocol` (not just `Callable`), and I'm not sure if we want that (requires Python 3.8).
> typing updates for Task

- sisyphus/aws_batch_engine.py
- sisyphus/load_sharing_facility_engine.py
- sisyphus/simple_linux_utility_for_resource_management_engine.py
- sisyphus/son_of_grid_engine.py
This was the root cause of several jobs with the same features being submitted, even though they had already been submitted:
1. We use the `gateway` option and there's a `TimeoutError` [here](https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/simple_linux_utility_for_resource_management_engine.py#L101).
2. From the point of view of sisyphus, the `ssh gw-02 squeue` finishes with error -1. Sisyphus then reaches [here](https://github.com/rwth-i6/sisyphus/blob/master/sisyphus/simple_linux_utility_for_resource_management_engine.py#L241) safely. It hasn't crashed with a `TimeoutError` because we haven't propagated it.
3. No `TimeoutError` is raised after calling `self.system_call()` because it's already been addressed inside `self.system_call()` and it hasn't been propagated. Therefore, …
> Catch `subprocess.TimeoutError` once

- sisyphus/global_settings.py
- sisyphus/job.py
When sisyphus cleans up a job folder, the input folder is deleted. This can be impractical if you want to find some job's dependencies because instead of just going through the input folders, you need to open each `finished.tar.gz` file and check for input jobs in the `info` file. I therefore propose to add the config option `JOB_CLEANUP_KEEP_INPUT`. It set to True, the input folder will remain even after cleaning.
Edit: As suggested in the PR, we set `JOB_CLEANUP_KEEP_INPUT = True` as the default setting. This changes the default behavior, but is not expected to hurt anyone.
> allow keeping input folder during job cleanup

- sisyphus/aws_batch_engine.py
- sisyphus/engine.py
- sisyphus/load_sharing_facility_engine.py
- sisyphus/localengine.py
- sisyphus/simple_linux_utility_for_resource_management_engine.py
- sisyphus/son_of_grid_engine.py
Fix #175.
Whenever the return value of the queue scan command is different from zero, the job states are eventually set as `UNKNOWN`. Whenever some job is set as `UNKNOWN` and there's no log file attached, the job will be automatically considered as `RUNNABLE` and queued.
This is a very dangerous process because there's usually a job already queued "naturally", that is, queued because the queue scan job finished gracefully, found nothing, and set the job state as `UNKNOWN`, thus queuing the job normally.
This wrong process can happen many times, until the first job scheduled eventually enters `RUNNING` state, and thus a log file is generated, preventing any further same job schedulings.
This PR fixes such wrong behavior by making the queue scan wait some seconds before rescheduling it …
> Queue scan: handle return value different from zero

- sisyphus/global_settings.py
- sisyphus/manager.py
Closes #179
Closes #204
now testing this
> Allow hooking job failure for generic error handling

- .github/workflows/main.yml
- sisyphus/hash.py
- tests/hash_unittest.py
Fix https://github.com/rwth-i6/sisyphus/issues/207
See #207 for some discussion.
Note that this slightly changes the behavior, but only for cases which were basically broken before.
E.g., for `functools.partial`, before this change, none of the relevant args (`func`, `args`, `keywords`) were ever part of the hash. So this change should not really break anything.
The same is also true for cases where there was both a `__dict__` and `__slots__`. With Python <=3.10, it would have used only the `__dict__`, and very likely, that was just empty, and does not contain any of the relevant things (which are very likely all in the `__slots__`), so it was totally broken and basically unusable. With Python >=3.11, there is a default `__getstate__` now, which would already do the correct thing, at …
> hash get_object_state, use dir for native types, fix __slots__ 

- sisyphus/hash.py
- sisyphus/tools.py
- tests/hash_unittest.py
- tests/tools_unittest.py
This fixes the same problems as #207 but now for `extract_paths`, by using the same shared code (`get_object_state`).
> extract_paths, use get_object_state

- sisyphus/job.py
- sisyphus/simple_linux_utility_for_resource_management_engine.py
- Wrap calls into `srun` (better resource tracking according to internet, also required to start `--ntasks > 1` at all)
- Add support for log file linking when multiple SLURM tasks are involved
> Adapt SLURM engine for multi-node jobs

- sisyphus/job.py
> Clarify the use of Job.set_rqmt and Job.update_rqmt

- sisyphus/manager.py
> Add threads for alias and output updates on startup

- sisyphus/graph.py
- sisyphus/manager.py
Via: https://github.com/rwth-i6/sisyphus/issues/167#issuecomment-2503673941
> Job cleaner, use own thread pool for graph traversal

- sisyphus/manager.py
Fix #224.
Follow-up to #214.
What I don't understand:
Why did I not get any exception?
Without this change, it just did not call the func (or I don't know, but at least it did not work, it did nothing).
> Fix async call of create_aliases

- sisyphus/manager.py
When `--run` is used, it will anyway still call create_aliases later, just in the same way as without the `--run` option.
> cleanup redundant create_aliases call

- sisyphus/global_settings.py
- sisyphus/manager.py
When running experiments in subgraphs I often encounter that only 3-4 trainings and nothing else is running. When only doing recognitions on e.g. the last checkpoint this causes the manager to not print an update for a long time. Since the Training job info also includes the current epoch, its desirable for me to print an update every x seconds.  
Thus I propose this flag that if set does this.
> Add timer to print update

- sisyphus/simple_linux_utility_for_resource_management_engine.py
Fix #229.
(Makes PR #230 obsolete.)
(This seems to be needed since we use an additional explicit `srun` via PR #212.)
> Slurm, fix ntasks per node to one

- sisyphus/graph.py
> for_all_nodes, handle exception/exit

- .github/workflows/black.yml
Python 3.7 not available anymore in CI.
> CI black: update Python

- sisyphus/simple_linux_utility_for_resource_management_engine.py
You might want to run `sis worker ...` directly to debug something.
> Slurm, fix when running sis worker outside Slurm env

- sisyphus/job_path.py
`AbstractPath` inherits from `DelayedBase`, but the implementation of `DelayedBase.is_set` https://github.com/rwth-i6/sisyphus/blob/a7a01653301f3098f7201eac7fbef4073f42b610/sisyphus/delayed_ops.py#L19-L20 is incompatible with `AbstractPath`, because it does not have `a` and `b`.
Fortunately `AbstractPath` implements a method `available` which we can use instead.
> Implement is_set for AbstractPath

- sisyphus/job.py
Small thing that annoys me from time to time: linking the job inputs fails with "File exists" if the creator path does not exist (and multiple inputs have same creator) because `isdir(broken_symlink) == False`.
If you run into this, clearly something else is wrong, but should fail at another place, not here.
> sis_setup_directory: fix crash on broken input symlink

- sisyphus/tools.py
The first change is related to the bug, the other 2 are style suggestions by my editor. The problem is that for a bytes object the cascade of if-else statements would fall through to the last else statement where we call `get_object_state` and the returned object has another byte object inside of it:
```
>>> sisyphus.tools.get_object_state(b"abc")                                                                                                                                                                                                                                             
((b'abc',), None) 
```
> Fix infinite loop bug in tools.extract_path

- .flake8
- .github/workflows/main.yml
- sisyphus/filesystem.py
- sisyphus/graph.py
- sisyphus/job.py
- sisyphus/job_path.py
- sisyphus/toolkit.py
- sisyphus/visualize.py
Currently CI fails with this message:
> This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101
>
> GitHub Actions has encountered an internal error when running your job.
I assume this would be fixed by this update.
Somewhat related is #195.
Fixes #246.
> CI test: use ubuntu-latest, Python 3.8

- sisyphus/graph.py
Example what it writes to the `log/finished.log` file now.
```
2025-03-08 22:03:09: Updated output: output/2024-denoising-lm/error_correction_model/base-spm10k-lsh10-epSplit20-keepSubwords-n1024-decL16-b2k_20k/recog-ext/dlm_sum_score_results.txt: .../JoinScoreResultsJob.U8Qm0RYyVsjz/output/score_results.json -> JoinScoreResultsJob.Glkc2ggQSUP3/output/score_results.json
2025-03-08 22:03:09: Finished output: output/2024-denoising-lm/error_correction_model/base-spm10k-lsh10-epSplit20-keepSubwords-n1024-decL16-b2k_20k/recog-ext/dlm_sum_score_results.txt (-> work/i6_experiments/users/zeyer/datasets/score_results/JoinScoreResultsJob.Glkc2ggQSUP3/output/score_results.json)
```
> finished log, also log updated outputs

- sisyphus/graph.py
- sisyphus/job.py
- sisyphus/manager.py
When you get the warning `Alias ... is used multiple times`, it will now also print the stacktrace of both jobs (if storing the stacktrace of each job was enabled, which it is not by default).
Along the way, I added some typing info.
> create_aliases, duplicates warning, print stack trace

- sisyphus/simple_linux_utility_for_resource_management_engine.py
It turns out, %A refers to different things in `sbatch` and in the wrapped `srun`, leading to broken log symlinks in the job folder :( 
%j seems to be consistent: https://slurm.schedmd.com/sbatch.html, I also confirmed locally.
Current behavior (pre-fix):
```
❯ ls work/config/create_corpora/CreateCsvFromAvroJob.Z8lxU0d8s4Dt/engine
config.create_corpora.CreateCsvFromAvroJob.Z8lxU0d8s4Dt.run.8344989.1
```
```
❯ ll work/config/create_corpora/CreateCsvFromAvroJob.Z8lxU0d8s4Dt/log.run.1
lrwxrwxrwx 1 mgunz domain_users 76 Mar 25 07:54 work/config/create_corpora/CreateCsvFromAvroJob.Z8lxU0d8s4Dt/log.run.1 -> engine/config.create_corpora.CreateCsvFromAvroJob.Z8lxU0d8s4Dt.run.8345118.1
```
```
❯ scontrol show jobid 8345118
JobId=8345118 ArrayJobId=8344989 ArrayTaskId=1 …
```
> Fix job IDs in SLURM log symlink not matching up

- sisyphus/global_settings.py
- sisyphus/job.py
I need this to update permissions on certain output files of some jobs. This seems like a good generic solution that can be used in other situations as well, just like `gs.on_job_failure`
> Add gs.on_job_finished callback

- .github/workflows/black.yml
Currently, the CI on black always fails like this:
```
Run actions/setup-python@v2
with:
python-version: 3.13
cache: pip
cache-dependency-path: .github/workflows/black.yml
token: ***
Successfully setup CPython (3.13.3)
/opt/hostedtoolcache/Python/3.13.3/x64/bin/pip cache dir
/home/runner/.cache/pip
Error: Cache service responded with 422
```
Related:
https://github.com/lukka/run-vcpkg/issues/243
https://github.com/microsoft/vcpkg/issues/45073
https://github.com/actions/cache/issues/1593
> CI fix caching for setup-python, update to v5

- sisyphus/delayed_ops.py
Previously calling `round(sisyphus_var, n)` caused an error.
> Add support for using `round(x, n)` on delayed items

- sisyphus/graph.py
Fix #256.
`OutputTarget.update_requirements` will update the internal state of the object, and that will change the output of `OutputTarget.__hash__`.
Any use of the hash (e.g. in `set`/`dict`), such as the use introduced in #255 to speed up `SISGraph.remove_from_active_targets`, is likely broken, when the state of the object changes. And this is the case in `Manager.check_output`, which calls `OutputTarget.update_requirements`.
This fixes `OutputTarget.__hash__` in a way that it does not change when the requirements change.
> fix OutputTarget __hash__

- sisyphus/toolkit.py
Just had a case where a wrongly done auto-import lead to confusing error messages for somebody who is new to sisyphus.
> Improve error message when wrong type of Path is passed

- sisyphus/delayed_ops.py
- sisyphus/tools.py
To do something like:
```
models = {1: model_eopch1, 2: model_epoch2, ...}
best_epoch = SelectBestEpochJob(all_scores).out  # tk.Variable
best_model = tk.Delayed(models)[best_epoch]
```
Or just any situation where a dict key depends on a job output. Actually, should also work for list indexing.
`DelayedSlice` already supports both delayed iterable as well as delayed range start/end/step, so this is just the analogous thing for "simple" access.
> DelayedOps: dict.__getitem__ with delayed key
